### ISSUE TITLE
About GLUE data

### ISSUE THREAD

**Issue by yxgnahz** [YujieLu10/IACE-NLU#1]
Hi, I'm interested in your work.
I found one thing that is very confusing in download_glue_data.py. I notice that for downloading QQP the address is https://dl.fbaipublicfiles.com/glue/data/STS-B.zip' while for downloading STS-B the address is 'https://dl.fbaipublicfiles.com/glue/data/QQP-clean.zip'. Does this indicate the GLUE results in your paper are reversed for QQP and STS-B?
Thanks in advance.

**Comment by YujieLu10** [comment]
Hi, thank you for pointing it out. Actually, you can refer to https://raw.githubusercontent.com/huggingface/transformers/master/utils/download_glue_data.py for downloading the data, which is also what I did. So the results are not reversed. But I uploaded the wrong version of download_glue_data.py. I just updated the correct one.

**Comment by yxgnahz** [comment]
Thanks very much for your response!
I tried "https://raw.githubusercontent.com/huggingface/transformers/master/utils/download_glue_data.py", however, I met an error: "HTTP Error 403: Forbidden". It seems that we do not have the access to it? Therefore, could you share us the glue dataset used in your repo via Google Drive?
Many thanks.

**Comment by YujieLu10** [comment]
Hi, I'm not sure why you get into this error. Can you try downloading directly from the path link?
