### ISSUE TITLE
extract_subset.py  not found

### ISSUE THREAD

**Issue by 1024er** [YujieLu10/IACE-NLU#2]
extract_subset.py not found, will you please take a look at this question ? thank you

**Comment by YujieLu10** [comment]
Sorry for the confusion here. This part is actually moved to the run_glue_ima.py, where you can extract the subset with the argument "--train_data_percentage".

**Comment by 1024er** [comment]
extract_feature.py: error: unrecognized arguments: -rp glue

**Comment by YujieLu10** [comment]
> extract_feature.py: error: unrecognized arguments: -rp glue

typo fix: "-rp" change to "-nlu_dataset"

**Comment by Mingxiao-Li** [comment]
> extract_feature.py: error: unrecognized arguments: -rp glue

Hi, did you generate all images for glue dataset ?
